dist: trusty
language: cpp
compiler: gcc
install: export CXX="g++-8"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8
notifications:
 email:
  on_success: never
  on_failure: always
before_install: sudo apt-get update -qq
script: mkdir test/build && cd test/build && cmake -DCMAKE_BUILD_TYPE=Release ../ && make && ./morton-nd
