dist: bionic
language: cpp
compiler: gcc
install: export CXX="g++-9"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-9
notifications:
 email:
  on_success: never
  on_failure: always
before_install: sudo apt-get update -qq
script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ../ && make all && make test
